//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcHut.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int product_id { get; set; }
        public string product_name { get; set; }
        public int brand_id { get; set; }
        public int category_id { get; set; }
        public int status { get; set; }
        public string warranty { get; set; }
        public double price { get; set; }
        public string image { get; set; }
        public string specification { get; set; }
        public string Special { get; set; }
    
        public virtual brand brand { get; set; }
        public virtual category category { get; set; }
    }
}
